first
makgig/go-db-sql-final pull request #1
Opened 2024-10-16 17:48 UTC by makgig

2024-10-16 18:22 UTC, dirtymew approved these changes
Привет Максим

хорошая робота - но есть замечания

см PR

2024-10-16 18:22 UTC, dirtymew commented on parcel.go
> +	}
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-10-16 18:22 UTC, dirtymew commented on parcel_test.go
> +	require.Equal(t, parcel.Client, storedParcel.Client)
проще сравнить структуры чем каждое поле

2024-10-16 18:22 UTC, dirtymew commented on parcel_test.go
> +	require.Error(t, err)
еще хорошо бы ошибку проверить

assert.ErrorIs

2024-10-16 18:22 UTC, dirtymew commented on parcel_test.go
> +	require.Equal(t, newStatus, storedParcel.Status)
assert

2024-10-16 18:22 UTC, dirtymew commented on parcel_test.go
> +	require.Len(t, storedParcels, len(parcels))
assert

2024-10-16 18:23 UTC, dirtymew requested changes
.

2024-10-22 19:11 UTC, makgig commented on parcel.go
> +	}
commit second

2024-10-22 19:11 UTC, makgig commented on parcel_test.go
> +	require.Equal(t, parcel.Client, storedParcel.Client)
commit second

2024-10-22 19:11 UTC, makgig commented on parcel_test.go
> +	require.Error(t, err)
commit second

2024-10-22 19:12 UTC, makgig commented on parcel_test.go
> +	require.Equal(t, newStatus, storedParcel.Status)
commit second

2024-10-22 19:12 UTC, makgig commented on parcel_test.go
> +	require.Len(t, storedParcels, len(parcels))
commit second

2024-10-23 08:51 UTC, dirtymew approved these changes
Привет Максим

все ок

зачет

2024-10-23 08:51 UTC, dirtymew commented on parcel_test.go
> +		require.Equal(t, originalParcel.Client, parcel.Client)
assert.Equal(t, originalParcel, parcel)

2024-11-26 14:35 UTC, merged